name = "spearyx-frontend"
compatibility_date = "2025-09-15"

[env.production]
# Cloudflare Pages configuration
[env.production.pages_build_output_dir]
directory = "./dist"

# Enable logging
[env.production.logging]
level = "info"

# Analytics and monitoring
[env.production.analytics]
enabled = true

# Observability
[env.production.observability]
enabled = true
head_sampling_rate = 1

# Security headers
[env.production.security_headers]
strict_transport_security = "max-age=31536000; includeSubDomains"
x_frame_options = "DENY"
x_content_type_options = "nosniff"
referrer_policy = "strict-origin-when-cross-origin"

# CORS configuration
[env.production.cors]
allowed_origins = [
  "http://localhost:5173",
  "https://localhost:5173", 
  "http://127.0.0.1:5173",
  "https://127.0.0.1:5173"
]
allowed_methods = ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
allowed_headers = ["Content-Type", "Authorization", "X-Requested-With"]
allow_credentials = true
max_age = 86400

# Cache settings
[env.production.cache]
browser_ttl = 86400
edge_ttl = 86400

# Environment variables (if needed)
# [env.production.vars]
# NODE_ENV = "production"
